### ISSUE TITLE
How to compute cumulative beam blockage

### ISSUE THREAD

**Issue by heistermann** [wradlib/wradlib#105]
In our notebook `beamblockage/wradlib_beamblock.ipynb`, we compute the cumulative beamblockage fraction this way: find the maximum fraction along a beam, then set every bin *before* that to the beam bloackage fraction PBB, and everything *after* that to the maximum value. I think this is incorrect in cases where we have local maxima *before* the absolute maximum. Please have a look at the following image: Would you agree that it should look like the "new implementation"?

![beamblock](https://cloud.githubusercontent.com/assets/7724047/18700785/8128bb22-7fd9-11e6-8617-00a3138c47ac.png)

If you agree, I would change the notebook accordingly. I would also add a convenience function to `wraldib.qual` in order to compute the cumulative beam blockage fraction. I would add all this to Pull Request #104.

**Comment by kmuehlbauer** [comment]
@heistermann Believe it or not, I'm working this morning with the beamblock notebook for incorporation in a radar lecture. Good catch! :+1: for fixing and convenience function.

**Comment by kmuehlbauer** [comment]
@heistermann BTW, do you know or have seen a matplotlib based plot, where the coordinate system is curvilinear to see the earth's curvature? I'm trying to get this in for better representation.

**Comment by heistermann** [comment]
Sorry, I don't.
