### ISSUE TITLE
plot netcdf

### ISSUE THREAD

**Issue by godofyoga** [wradlib/wradlib#112]
Hello ,
 I am having netcdf file of X-Band EEC radar and it consist 17 elevation angle with different radar parameters.
I able to read file using following code in wradlib.
import wradlib as wb
import pylab as pl
filename = '/home/user/20140421/y20140421/MDV-20140421-130257-PPIVol.nc'
netcdf_f =wb.io.read_generic_netcdf(filename)
print netcdf_f['variables']

I unable to plot date so how can i separate each elevation angle data and make plot?

Thank you.

**Comment by wradlib** [comment]
Hi Yogesh,

in order to get an impression of the nc-file, could you attach the 
output of

`ncdump -h /home/user/20140421/y20140421/MDV-20140421-130257-PPIVol.nc`

It's also of interest, if this is just radardata within netcdf or 
complying to some standard (eg. cfradial).

Thanks,
Kai





Am 17.10.2016 um 14:03 schrieb yogesh kolte:
> Hello ,
>  I am having netcdf file of X-Band EEC radar and it consist 17 elevation angle with different radar parameters.
> I able to read file using following code in wradlib.
> import wradlib as wb
> import pylab as pl
> filename = '/home/user/20140421/y20140421/MDV-20140421-130257-PPIVol.nc'
> netcdf_f =wb.io.read_generic_netcdf(filename)
> print netcdf_f['variables']
>
> I unable to plot date so how can i separate each elevation angle data and make plot?
>
> Thank you.
>

**Comment by kmuehlbauer** [comment]
@godofyoga 

In order to get an impression of the nc-file, could you attach the output of 

`ncdump -h /home/user/20140421/y20140421/MDV-20140421-130257-PPIVol.nc` 

It's also of interest, if this is just radardata within netcdf or complying to some standard (eg. cfradial).

**Comment by godofyoga** [comment]
netcdf MDV-20140421-130257-PPIVol {
dimensions:
	time = 13896 ;
	range = 2500 ;
	sweep = 18 ;
	frequency = 1 ;
	string_length_sm = 10 ;
	string_length_md = 25 ;
variables:
	int volume_number ;
		volume_number:standard_name = "data_volume_index_number" ;
		volume_number:units = "1" ;
	double latitude ;
		latitude:standard_name = "latitude" ;
		latitude:units = "degrees_north" ;
	double longitude ;
		longitude:standard_name = "longitude" ;
		longitude:units = "degrees_east" ;
	double altitude ;
		altitude:standard_name = "altitude" ;
		altitude:units = "meters" ;
	char time_coverage_start(string_length_md) ;
		time_coverage_start:standard_name = "data_volume_start_time_utc" ;
		time_coverage_start:units = "1" ;
	char time_coverage_end(string_length_md) ;
		time_coverage_end:standard_name = "data_volume_end_time_utc" ;
		time_coverage_end:units = "1" ;
	double time(time) ;
		time:standard_name = "time" ;
		time:long_name = "time in seconds since volume start" ;
		time:units = "seconds since 2014-04-21T13:02:57Z" ;
	float azimuth(time) ;
		azimuth:standard_name = "beam_azimuth_angle" ;
		azimuth:long_name = "azimuth_angle_from_true_north" ;
		azimuth:units = "degrees" ;
		azimuth:axis = "radial_azimuth_coordinate" ;
	float elevation(time) ;
		elevation:standard_name = "beam_elevation_angle" ;
		elevation:long_name = "elevation_angle_from_horizontal_plane" ;
		elevation:units = "degrees" ;
		elevation:axis = "radial_elevation_coordinate" ;
	float radar_antenna_gain_h ;
		radar_antenna_gain_h:meta_group = "radar_parameters" ;
		radar_antenna_gain_h:standard_name = "nominal_radar_antenna_gain_h_channel" ;
		radar_antenna_gain_h:units = "dB" ;
	float radar_antenna_gain_v ;
		radar_antenna_gain_v:meta_group = "radar_parameters" ;
		radar_antenna_gain_v:standard_name = "nominal_radar_antenna_gain_v_channel" ;
		radar_antenna_gain_v:units = "dB" ;
	float radar_beam_width_h ;
		radar_beam_width_h:meta_group = "radar_parameters" ;
		radar_beam_width_h:standard_name = "half_power_radar_beam_width_h_channel" ;
		radar_beam_width_h:units = "degrees" ;
	float radar_beam_width_v ;
		radar_beam_width_v:meta_group = "radar_parameters" ;
		radar_beam_width_v:standard_name = "half_power_radar_beam_width_v_channel" ;
		radar_beam_width_v:units = "degrees" ;
	float radar_receiver_bandwidth ;
		radar_receiver_bandwidth:meta_group = "radar_parameters" ;
		radar_receiver_bandwidth:standard_name = "radar_receiver_bandwidth" ;
		radar_receiver_bandwidth:units = "s-1" ;
	float frequency(frequency) ;
		frequency:meta_group = "instrument_parameters" ;
		frequency:standard_name = "radiation_frequency" ;
		frequency:units = "s-1" ;
	float radar_measured_transmit_power_h(time) ;
		radar_measured_transmit_power_h:meta_group = "radar_parameters" ;
		radar_measured_transmit_power_h:standard_name = "radar_transmit_power_h_channel" ;
		radar_measured_transmit_power_h:units = "watts" ;
	float radar_measured_transmit_power_v(time) ;
		radar_measured_transmit_power_v:meta_group = "radar_parameters" ;
		radar_measured_transmit_power_v:standard_name = "radar_transmit_power_v_channel" ;
		radar_measured_transmit_power_v:units = "watts" ;
	float pulse_width(time) ;
		pulse_width:meta_group = "instrument_parameters" ;
		pulse_width:standard_name = "transmitter_pulse_width" ;
		pulse_width:units = "seconds" ;
	float prt(time) ;
		prt:meta_group = "instrument_parameters" ;
		prt:standard_name = "pulse_repetition_time" ;
		prt:units = "seconds" ;
	float prt_ratio(time) ;
		prt_ratio:meta_group = "instrument_parameters" ;
		prt_ratio:standard_name = "multiple_pulse_repetition_frequency_ratio" ;
	float nyquist_velocity(time) ;
		nyquist_velocity:meta_group = "instrument_parameters" ;
		nyquist_velocity:standard_name = "unambiguous_doppler_velocity" ;
		nyquist_velocity:units = "m/s" ;
	int n_samples(time) ;
		n_samples:meta_group = "instrument_parameters" ;
		n_samples:standard_name = "number_of_samples_used_to_compute_moments" ;
	char prt_mode(sweep, string_length_sm) ;
		prt_mode:meta_group = "instrument_parameters" ;
		prt_mode:standard_name = "transmit_pulse_mode" ;
	char polarization_mode(sweep, string_length_sm) ;
		polarization_mode:meta_group = "instrument_parameters" ;
		polarization_mode:standard_name = "transmit_receive_polarization_mode" ;
	float range(range) ;
		range:standard_name = "projection_range_coordinate" ;
		range:long_name = "range_to_measurement_volume" ;
		range:units = "meters" ;
		range:spacing_is_constant = "true" ;
		range:meters_to_center_of_first_gate = 25.f ;
		range:meters_between_gates = 50.f ;
		range:axis = "radial_range_coordinate" ;
	int sweep_number(sweep) ;
		sweep_number:standard_name = "sweep_index_number_0_based" ;
		sweep_number:units = "1" ;
	char sweep_mode(sweep, string_length_sm) ;
		sweep_mode:standard_name = "scan_mode_for_sweep" ;
		sweep_mode:units = "1" ;
	float fixed_angle(sweep) ;
		fixed_angle:standard_name = "target_fixed_angle" ;
		fixed_angle:units = "degrees" ;
	int sweep_start_ray_index(sweep) ;
		sweep_start_ray_index:standard_name = "index_of_first_ray_in_sweep" ;
		sweep_start_ray_index:units = "1" ;
	int sweep_end_ray_index(sweep) ;
		sweep_end_ray_index:standard_name = "index_of_last_ray_in_sweep" ;
		sweep_end_ray_index:units = "1" ;
	short UH(time, range) ;
		UH:long_name = "unfiltered_reflectivity_factor_h" ;
		UH:units = "dBZ" ;
		UH:_FillValue = -32768s ;
		UH:scale_factor = 0.01f ;
		UH:add_offset = 0.f ;
		UH:coordinates = "elevation azimuth range" ;
	short UV(time, range) ;
		UV:long_name = "unfiltered_reflectivity_factor_v" ;
		UV:units = "dBZ" ;
		UV:_FillValue = -32768s ;
		UV:scale_factor = 0.01f ;
		UV:add_offset = 0.f ;
		UV:coordinates = "elevation azimuth range" ;
	short DBZH(time, range) ;
		DBZH:long_name = "equivalent_reflectivity_factor_h" ;
		DBZH:units = "dBZ" ;
		DBZH:_FillValue = -32768s ;
		DBZH:scale_factor = 0.01f ;
		DBZH:add_offset = 0.f ;
		DBZH:coordinates = "elevation azimuth range" ;
	short DBZV(time, range) ;
		DBZV:long_name = "equivalent_reflectivity_factor_v" ;
		DBZV:units = "dBZ" ;
		DBZV:_FillValue = -32768s ;
		DBZV:scale_factor = 0.01f ;
		DBZV:add_offset = 0.f ;
		DBZV:coordinates = "elevation azimuth range" ;
	short ZDR(time, range) ;
		ZDR:long_name = "log_differential_reflectivity_hv" ;
		ZDR:units = "dBZ" ;
		ZDR:_FillValue = -32768s ;
		ZDR:scale_factor = 0.01f ;
		ZDR:add_offset = 0.f ;
		ZDR:coordinates = "elevation azimuth range" ;
	short RHOHV(time, range) ;
		RHOHV:long_name = "cross_correlation_ratio_hv" ;
		RHOHV:units = "1" ;
		RHOHV:_FillValue = -32768s ;
		RHOHV:scale_factor = 0.0001f ;
		RHOHV:add_offset = 0.f ;
		RHOHV:coordinates = "elevation azimuth range" ;
	short PHIDP(time, range) ;
		PHIDP:long_name = "differential_phase_hv" ;
		PHIDP:units = "degrees" ;
		PHIDP:_FillValue = -32768s ;
		PHIDP:scale_factor = 0.02f ;
		PHIDP:add_offset = 0.f ;
		PHIDP:coordinates = "elevation azimuth range" ;
	short NCPH(time, range) ;
		NCPH:long_name = "normalized_coherent_power_h" ;
		NCPH:units = "1" ;
		NCPH:_FillValue = -32768s ;
		NCPH:scale_factor = 0.0001f ;
		NCPH:add_offset = 0.f ;
		NCPH:coordinates = "elevation azimuth range" ;
	short NCPV(time, range) ;
		NCPV:long_name = "normalized_coherent_power_v" ;
		NCPV:units = "1" ;
		NCPV:_FillValue = -32768s ;
		NCPV:scale_factor = 0.0001f ;
		NCPV:add_offset = 0.f ;
		NCPV:coordinates = "elevation azimuth range" ;
	short SNRHC(time, range) ;
		SNRHC:long_name = "signal_to_noise_ratio_co_polar_h" ;
		SNRHC:units = "dB" ;
		SNRHC:_FillValue = -32768s ;
		SNRHC:scale_factor = 0.01f ;
		SNRHC:add_offset = 0.f ;
		SNRHC:coordinates = "elevation azimuth range" ;
	short SNRVC(time, range) ;
		SNRVC:long_name = "signal_to_noise_ratio_co_polar_v" ;
		SNRVC:units = "dB" ;
		SNRVC:_FillValue = -32768s ;
		SNRVC:scale_factor = 0.01f ;
		SNRVC:add_offset = 0.f ;
		SNRVC:coordinates = "elevation azimuth range" ;
	short VELH(time, range) ;
		VELH:long_name = "radial_velocity_h" ;
		VELH:units = "m/s" ;
		VELH:_FillValue = -32768s ;
		VELH:scale_factor = 0.01f ;
		VELH:add_offset = 0.f ;
		VELH:coordinates = "elevation azimuth range" ;
	short VELV(time, range) ;
		VELV:long_name = "radial_velocity_v" ;
		VELV:units = "m/s" ;
		VELV:_FillValue = -32768s ;
		VELV:scale_factor = 0.01f ;
		VELV:add_offset = 0.f ;
		VELV:coordinates = "elevation azimuth range" ;
	short WIDTHH(time, range) ;
		WIDTHH:long_name = "doppler_spectrum_width_h" ;
		WIDTHH:units = "m/s" ;
		WIDTHH:_FillValue = -32768s ;
		WIDTHH:scale_factor = 0.01f ;
		WIDTHH:add_offset = 0.f ;
		WIDTHH:coordinates = "elevation azimuth range" ;
	short WIDTHV(time, range) ;
		WIDTHV:long_name = "doppler_spectrum_width_v" ;
		WIDTHV:units = "m/s" ;
		WIDTHV:_FillValue = -32768s ;
		WIDTHV:scale_factor = 0.01f ;
		WIDTHV:add_offset = 0.f ;
		WIDTHV:coordinates = "elevation azimuth range" ;
	short CCORH(time, range) ;
		CCORH:long_name = "clutter_correction_h" ;
		CCORH:units = "dB" ;
		CCORH:_FillValue = -32768s ;
		CCORH:scale_factor = 0.01f ;
		CCORH:add_offset = 0.f ;
		CCORH:coordinates = "elevation azimuth range" ;
	short CCORV(time, range) ;
		CCORV:long_name = "clutter_correction_v" ;
		CCORV:units = "dB" ;
		CCORV:_FillValue = -32768s ;
		CCORV:scale_factor = 0.01f ;
		CCORV:add_offset = 0.f ;
		CCORV:coordinates = "elevation azimuth range" ;

// global attributes:
		:Conventions = "Cf/Radial instrument_parameters radar_parameters" ;
		:title = "PPIVol" ;
		:institution = "EEC" ;
		:references = "EEC" ;
		:source = "EDGE" ;
		:history = "original" ;
		:comment = "PPIVol" ;
		:instrument_name = "MDV" ;
		:site_name = "MDV" ;
		:n_gates_vary = "false" ;
}

**Comment by kmuehlbauer** [comment]
It's cfradial (See the Conventions attribute). My suggestion would be to use `pyart` to read the data.

**Comment by godofyoga** [comment]
I am using Py-Art also but how can i use radar object of pyart in wradlib and make plot.
I want to use attenuation correction in wradlib.

**Comment by kmuehlbauer** [comment]
You can't use the part radar object out of the box. But you can extract the needed features/moments from the radar object as bumpy arrays and use them within wradlib. 

Let me know, if you need more help with this extraction. I can come back to this early next week.

**Comment by kmuehlbauer** [comment]
@godofyoga Is this still an issue? Have you been successful in extracting the needed data?

**Comment by godofyoga** [comment]
I able to plot data with py-Art but not with wradlib. I want to use attenuation correction algorithms in wradlib.

Please help me

**Comment by kmuehlbauer** [comment]
Can you share a minimal plotting example for `py-art`. Then I can better assist you in extracting the wanted data from the nc-file.

Also, sharing an example data file would be nice. You can send all to the mailinglist (wradlib-users@googlegroups.com).

**Comment by kmuehlbauer** [comment]
resolved by [this post](https://groups.google.com/d/msg/wradlib-users/5Vgdn5vtVMg/PcuMd_oRCgAJ) on the wradlib user forum.
