### ISSUE TITLE
[3D-Matching]: GR/PR indices match-up

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradlib#121]
For the calculation of PR-Grids within the GR radar domain I suggest using `ZonalDataPoint` and `GridPointsToPoly`.

```python
gr_domain = gr_xy[:,-1,:]
gr_domain = np.vstack((gr_domain, gr_domain[0]))
l_gr = []
l_gr.append(gr_domain)

zd = wradlib.zonalstats.ZonalDataPoint(pr_xy.reshape(-1, pr_xy.shape[-1]), l_gr, srs=rad, buf=0.)
obj1 = wradlib.zonalstats.GridPointsToPoly(zd)
```

As the PR-Data is only 176x49 this is outstanding fast. And we could think about the possibility to add attributes to the points in the object. We also might think about creating polygonic footprints from the PR-Data and do the same to find matching GR-bins.

In the attached image you can see which points are considered with the method in IDL (simple bounds) and using the zonal-approach. 

![points_match](https://cloud.githubusercontent.com/assets/5821660/20170532/040a8e92-a72d-11e6-986f-13fd19df6ac7.png)

**Comment by heistermann** [comment]
This is exactly what I was hoping for - to make some use of `zonalstats` for the 2-D components of the analysis.

**Comment by kmuehlbauer** [comment]
see #129
