### ISSUE TITLE
[3D-Matching]: PR/GR Pulse Volume 

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradlib#123]
The original IDL-code uses [Small-angle approximation](https://en.wikipedia.org/wiki/Small-angle_approximation) to calculate the tangent of `theta` (equals radius of the beam cone frustum). Also it assumes the cone frustum being a cylinder, which simplifies more.

The wradlib-function [wradlib.qual.pulse_volume()](https://github.com/wradlib/wradlib/blob/master/wradlib/qual.py#L119) uses this cylinder simplification too, but doesn't use the small-angle approximation. 

@heistermann If I'm not mistaken the wradlib function is missing a factor of 0.5 in the tangent-angle calculation. Correcting this, we can use the `pulse_volume()`-function to calculate pulse volume of PR/GR pulses.

**Comment by heistermann** [comment]
@kmuehlbauer dammit you're right. We need to use half of the aperture angle to get the base radius of the cone (or cylinder). Well, this bug was long asleep...should I push an immediate fix?

**Comment by heistermann** [comment]
See Pull Request #124.

**Comment by kmuehlbauer** [comment]
Merged #124
