### ISSUE TITLE
ZeroDivisionError when PR has no overlap with GR data in matching workflow

### ISSUE THREAD

**Issue by IreneCrisologo** [wradlib/wradlib#145]
In the step where the precipitation mask is generated (under **Subset relevant PR data**), the line `precip_mask = (pflag == 2) & wradlib.zonalstats.get_clip_mask(pr_xy, gr_domain, rad)`  produces a `ZeroDivisionError` when there is no overlap between the overpass array and ground radar data. 

I'm not sure if this should be caught somehow in the workflow, but i'm just reporting it in case someone encounters the same issue and cannot figure out the reason why the error occurs. It took some time to figure out, for me at least.

**Comment by kmuehlbauer** [comment]
@IreneCrisologo 

This is actually a problem of the underlying ZonalData object. If there is no intersection the `dst` layer is empty. This leads to this faulty behaviour.

How should we tackle this? @heistermann We could add a property `has_intersections` (or similar) and test this before starting calculation.

**Comment by kmuehlbauer** [comment]
Current workflow:

When creating the `ZonalDataPoint` or `ZonalDataPoly`, we assume that there will be intersections. This leads to the creation of a empty `dst` DataSource (DataSource with empty Layer). This is never tested in the subsequent processing.

Proposal:
We add a property `intersection_count` to `ZonalDataBase` and add the count there at creation time. We only create `GridPointsToPoly` or `GridCellsToPoly` if `intersection_count` is greater than 0.

**Comment by heistermann** [comment]
:+1:

**Comment by kmuehlbauer** [comment]
fixed in #215
