### ISSUE TITLE
Infinite loop when trying to read an empty RADOLAN file

### ISSUE THREAD

**Issue by doktormerlin** [wradlib/wradlib#184]
If you read an empty (possibly also a corrupt) RADOLAN file, the execution gets stuck in an infinite loop in `wradlib.io.read_radolan_header(fid)`

This seems to be due to no check, if there is any input available. The code only checks for the EOT char to break the while(True) loop, but doesnt stop if it is an empty character.

**Comment by kmuehlbauer** [comment]
@doktormerlin Thank you for reporting. The issue is taken care of in #185.
