### ISSUE TITLE
Remove time series functions from wradlib.util

### ISSUE THREAD

**Issue by heistermann** [wradlib/wradlib#216]
There are a couple of functions related to processing time series in `wradlib.util` that should be deprecated and then removed with v1.0.

```
- aggregate_equidistant_tseries
- aggregate_in_time
- sum_over_time_windows
- mean_over_time_windows
- average_over_time_windows
```

These are all experimental and never became mature. Only speaking for myslef, but I do not use them anymore.

There are some related helper functions that could also be removed:

```
- _get_func
- _tdelta2seconds
- iso2datetime
- timestamp2index
```

There's only one function I am using routinely outside `wradlib.util`: `from_to` - I'll gladly leave it there, but I won't insist.

Apart from that, I think that in the future, time series processing should be "outsourced" to dedicated packages such as pandas (for tabular data) or xarray (for multi-dimensional data). Maybe we can develop some tutorials...someday.

**Comment by kmuehlbauer** [comment]
👍  @heistermann I was about to add an issue on stuff to deprecate. There are some more things we could think of cleaning up.
