### ISSUE TITLE
Revise structure of some of the ipol-classes

### ISSUE THREAD

**Issue by heistermann** [wradlib/wradlib#255]
Check which class variables should be transformed to class properties.

**Comment by kmuehlbauer** [comment]
Checking back almost 5 years later :grinning:

I'm using the ipol-classes quite frequently and they are still extremely useful. Most of the time I'm creating the interpolator-instance once and re-use it wrapped for xarray with apply_ufunc. Maybe we can add some apply_ufunc-wrapper for the xarray-based radar data.

**Comment by kmuehlbauer** [comment]
This will get traction in wradlib 2.0.
