### ISSUE TITLE
read_Rainbow not closing file properly

### ISSUE THREAD

**Issue by meteoswiss-mdr** [wradlib/wradlib#267]
Dear wradlib masters,

When using wradlib.io.read_Rainbow to read a rainbow file I get the following warning:
unclosed file <_io.BufferedReader name='[name_of_file.vol]'>

I am using wradlib version 0.11.3 with python version 3.6.4.

Could you please have a look at it?

Thanks!

**Comment by kmuehlbauer** [comment]
@meteoswiss-mdr We would need the rainbow source file to debug this.

**Comment by meteoswiss-mdr** [comment]
@kmuehlbauer, can I send it by private email?

**Comment by kmuehlbauer** [comment]
@meteoswiss-mdr Sure. I think you have my email address. Otherwise, you'll find it via the link in my github-bio.

**Comment by kmuehlbauer** [comment]
@heistermann If `read_rainbow` is called with a string, the file is opened, but never closed. This might lead to this **Warning**. There are also other places where we do not properly close files, we have opened. We should adress this for the next minor release. WDYT?

**Comment by heistermann** [comment]
Absolutely. Maybe we can switch, at least for some cases, to use the `with` statement as it also handles closing in case of Exception that occur on the way before the `close` statement. Like
```
with open("x.txt") as f:
    data = f.read()
    do something with data
```

**Comment by kmuehlbauer** [comment]
Yes, I checked with @meteoswiss-mdr that this would be the most pythonic way. But we would need to see how this fits when we call with filehandle.

**Comment by kmuehlbauer** [comment]
@heistermann, We already use this construct in the tests.

**Comment by kmuehlbauer** [comment]
@meteoswiss-mdr Finally looking into this, I'm trying to recreate the warning with no luck. Could you provide a minimal example showing which issues this warning?
