### ISSUE TITLE
Implement ODIM Reader/Writer

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradlib#272]
Implement ODIM Reader/Writer from `rmilib` (suggested by @egouden)

**Comment by kmuehlbauer** [comment]
@egouden Thank you again for the quick introduction on your current work in `rmilib` at ERAD2018. We can track the upcoming implementation work in this issue.

**Comment by kmuehlbauer** [comment]
@egouden Is there anything we can do to get things along? We could create a private repo here for the implementation process. Would that be a way to go for you?

**Comment by egouden** [comment]
Hello,

Good to hear you!

Unfortunately the only blocking factor is time. I am mainly busy with
support and maintenance of my precipitation products, preparing
presentations and coordinating projects. I have hardly time for big
development. In fact the Odim module is my top priority development.
I want to finnish this very soon.
I already checked the Odim validator.
I give you the code next week to start collaborating in public 😉

See you soon.

Edouard

**Comment by kmuehlbauer** [comment]
resolved by #311
