### ISSUE TITLE
"from module import function" not recommended

### ISSUE THREAD

**Issue by egouden** [wradlib/wradlib#348]
It is generally recommended not to use "from module import function" to avoid circular imports.
This decreases readability too.

**Comment by kmuehlbauer** [comment]
@egouden Thanks for bringing this up!

Seems this is use throughout the project. So what is the suggestion then?

Instead of doing
```
from .projection import proj4_to_osr, reproject
```
we would do
```
from . import projection
```
and prepend `proj4_to_osr` and `reproject` with the module name (`projection`)

**Comment by kmuehlbauer** [comment]
Doing a quick search through the code I found these different usages for wradlib-modules:

importing modules
- `import wradlib.ipol as ipol` 
- `from . import trafo as trafo`  (same as `from . import trafo`)

Importing functions from modules
- `from .trafo import decibel`
- `from .io.xarray import create_xarray_dataarray`
- `from . util import import_optional`

For the rewrite of the import sections I would suggest to use relative imports:
- `from . import module`

Functions/Names should not be imported directly, the module should be imported instead.

There are some locations where we already have the import statement within the code to avoid circular dependencies, see https://github.com/wradlib/wradlib/blob/396235eeadf37dc261e37575bd93be2c762dce82/wradlib/util.py#L317 .  

This is open for discussion!

@egouden Can you imagine a more fitting issue title?

**Comment by egouden** [comment]
I would suggest using only import "wradlib.package as package" since our project is not that big.

**Comment by kmuehlbauer** [comment]
OK! If I got your suggestion right: Since we do not have a deeply nested package is would be more straightforward to go this way:

`import wradlib.clutter as clutter`
`import wradlib.io.dem as io.dem`

**Comment by egouden** [comment]
Not sure about how to deal with subpackage...

**Comment by kmuehlbauer** [comment]
@egouden Can we apply from this doc: https://docs.python.org/3/tutorial/modules.html#packages ?

**Comment by egouden** [comment]
Well this is the general documentation but I cannot find any recommendations regarding our issue.
Could you elaborate?
What I suggested above is what I think is best after a web search on the topic including discussions from the main python developers.
It is also recommended [here](https://docs.python-guide.org/writing/structure/).
I tend to prefer explicit imports of wradlib modules for readability and sustainability of the code but I am OK with relative imports.
