### ISSUE TITLE
Interpolation kwarg not passed to interpolator call method

### ISSUE THREAD

**Issue by jorahu** [wradlib/wradlib#373]
Using Nearest interpolator with maxdist kwarg when using wradlib.comp.togrid function does not work although togrid documentation says kwargs are passed to interpolator class. 
https://github.com/wradlib/wradlib/blob/d7e30e61bcdb6faed122e8b41926c88ef1650ed4/wradlib/comp.py#L89 calls the interpolator without maxdist kwarg. 
When calling the comp.togrid method with maxdist gives TypeError: TypeError: __init__() got an unexpected keyword argument 'maxdist'.

**Comment by kmuehlbauer** [comment]
@jorahu Sorry, this had to be postponed to the next (bugfix-) release. It's a bit more complicated thatn anticipated and might need an rewrite of the interpolator classes.

**Comment by kmuehlbauer** [comment]
@jorahu In #425 I've implemented a bit of a hack to get this in. You can add the calling keyword arguments by adding
```python
togrid(...,...,..., call_kwargs=dict(maxdist=10))
```
This will be available in wradlib 1.7 in about two weeks time.
