### ISSUE TITLE
Possible error on the notebook/documentation

### ISSUE THREAD

**Issue by ElmerJeanpierreLopez** [wradlib/wradlib#382]
In the notebook of BeamBlockage mentions that angle of elevation should be in deg. But, the documentation of the function sweep_centroids (https://docs.wradlib.org/en/latest/generated/wradlib.georef.polar.sweep_centroids.html) that use after says that elevation angle must be on rad. So, one of them there must be wrong.

**Comment by kmuehlbauer** [comment]
@ElmerJeanpierreLopez Thanks for reporting this issue. This is an error in the documentation of `sweep_centroids`. It should read `degrees`.

Would you be able to issue a PR to fix this?

**Comment by ElmerJeanpierreLopez** [comment]
Could be. But I don't know what means PR.

**Comment by ElmerJeanpierreLopez** [comment]
I feel so embarrassing. I already created a Pull Request of this.

**Comment by kmuehlbauer** [comment]
> I feel so embarrassing. I already created a Pull Request of this.

No worries, thanks for fixing this, your help is very much appreciated!
