### ISSUE TITLE
Google colab: env variable

### ISSUE THREAD

**Issue by kunalrustagi08** [wradlib/wradlib#411]
Hi. I am trying to use wradlib on google colab, but unable to set the environment variable for WRABLIB_DATA. 

I tried the way it was described in [this link](https://docs.wradlib.org/en/stable/jupyter.html#how-can-i-get-the-example-data), but got an OSError.
![Screenshot from 2020-03-10 21-27-35](https://user-images.githubusercontent.com/38221586/76332144-060a7380-6316-11ea-91c2-bc81d9d10808.png)
![Screenshot from 2020-03-10 21-30-54](https://user-images.githubusercontent.com/38221586/76332490-73b69f80-6316-11ea-8d3d-5661f0f48d99.png)

Can someone please help me how to set it using %env.

**Comment by kmuehlbauer** [comment]
@kunalrustagi08 You would need to replace the 'full/path/to/blabla' with the actual path where wradlib-data is installed.

**Comment by kunalrustagi08** [comment]
> @kunalrustagi08 You would need to replace the 'full/path/to/blabla' with the actual path where wradlib-data is installed.

Sorry, but I am not able to find the path of wradlib_data in google colab. Can you please help?

**Comment by kmuehlbauer** [comment]
It's not there in colab until you install/upload it.



Am 11. März 2020 06:57:51 MEZ schrieb Kunal Rustagi <notifications@github.com>:
>> @kunalrustagi08 You would need to replace the 'full/path/to/blabla'
>with the actual path where wradlib-data is installed.
>
>Sorry, but I am not able to find the path of wradlib_data in google
>colab. Can you please help?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/wradlib/wradlib/issues/411#issuecomment-597457686

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by kunalrustagi08** [comment]
I have successfully installed wradlib using pip, still getting the error.
![Screenshot from 2020-03-11 13-37-46](https://user-images.githubusercontent.com/38221586/76395563-a3f55100-639d-11ea-89ec-65512c8e580e.png)

**Comment by kmuehlbauer** [comment]
@kunalrustagi08 You need to follow the docs. In the link you provided in your first post, there is written:

*Most notebooks use example data. These data are provided in a separate repository and you need to “install” them manually. “Installing” actually means: Download the data archive [here](https://codeload.github.com/wradlib/wradlib-data/zip/master) and extract it into any arbitrary directory. Now you need to set an environment variable pointing to that directory:*

You need to download the data archive supplied within the link, extract it to some location where you can access it and then point `WRADLIB_DATA` env variable to this location.

**Comment by kunalrustagi08** [comment]
Hey. I just realized my mistake that I overlooked the simple instructions. Thank you for pointing it out to me. Now it is working fine. :)

**Comment by kmuehlbauer** [comment]
@kunalrustagi08 Glad you got it working. Next time, if you have some user question which is not directly related to the code itself, please use the [wradlib-user group](https://groups.google.com/forum/#!forum/wradlib-users).

**Comment by kunalrustagi08** [comment]
> @kunalrustagi08 Glad you got it working. Next time, if you have some user question which is not directly related to the code itself, please use the [wradlib-user group](https://groups.google.com/forum/#!forum/wradlib-users).

Yes. Definitely!
