### ISSUE TITLE
DWD WN RADOLAN Grid 1200x1100

### ISSUE THREAD

**Issue by julste** [wradlib/wradlib#448]
Hi there!

Since the FX radar product isn't available on September 30, 2020 anymore but its successor product WN radar product ([https://www.dwd.de/DE/leistungen/opendata/neuigkeiten/opendata_jul2020_01.html](https://www.dwd.de/DE/leistungen/opendata/neuigkeiten/opendata_jul2020_01.html)), is it possible to support a 1200 x 1100 Grid? Because the WN-Composit is using 1200 x 1100 as you can see [here](https://www.dwd.de/DE/leistungen/radarprodukte/radarkomposit_wn.pdf?__blob=publicationFile&v=3). 

And is there a workaround so far?

I tried other dimensions like the extended one, but their are incompatible:

`TypeError: Dimensions of C (1200, 1100) are incompatible with X (1400) and/or Y (1500); see help(pcolormesh)
`

**Comment by kmuehlbauer** [comment]
@julste Thanks for bringing this to attention. I think it should be possible to implement and cut a release before September 30th.

**Comment by kmuehlbauer** [comment]
@julste The 1200,1000 grid is implemented in #449. You can install wradlib from github master to test. This will be available in the next release.
