### ISSUE TITLE
Modification of the header parser in io.read_dx 

### ISSUE THREAD

**Issue by GolGosh** [wradlib/wradlib#455]
Hi dear community,

I am working with dx radar product from DWD (the German Weather Service) and the new batch of dx files that they provided to me for a new radar location are causing the following error in the first step if my processing in the wrl.io.read_dx(dx) function:

     "ValueError: could not convert string to float: 'X01'"

Could anyone tell me if this is a problem from the files or if I can fix in on my own?

Thanks!

**Comment by kmuehlbauer** [comment]
This is the header in question 

`DX010000109080100BY 4173VS 1CO2CD2CS0MS***XXXXXXXX`

and this is a newer header of the same radar station:

`DX161015109080920BY57169VS 2CO0CD4CS0EP0.30.30.40.40.50.40.40.2MS  0`

One can see, that the `EP ` signature wasn't available at that time and that `MS` signature has some undefined * and X. So the parser should be modified to overcome this problem.

https://github.com/wradlib/wradlib/blob/1f449ea65aa96f1e2bd056b6427825fdbe4035f3/wradlib/io/radolan.py#L153-L160
