### ISSUE TITLE
wradlib installation problem

### ISSUE THREAD

**Issue by babuvanam** [wradlib/wradlib#489]
i am new to python ,
i have installed wradlib in my system through anaconda prompt ,but when i import it in my program i am getting error:"No mudule named 'wradlib' ",please help me,thanks in advance
![Capture](https://user-images.githubusercontent.com/83119962/115957149-72e2cc00-a51e-11eb-9471-702d8dc4cbf1.PNG)
![Capture1](https://user-images.githubusercontent.com/83119962/115957155-79714380-a51e-11eb-8187-9b49c4a04256.PNG)
![Capture3](https://user-images.githubusercontent.com/83119962/115957161-7e35f780-a51e-11eb-89ed-1a5616d691d1.PNG)

**Comment by babuvanam** [comment]
here are the screenshots
![Capture](https://user-images.githubusercontent.com/83119962/115957098-33b47b00-a51e-11eb-97a9-85e341a9d4fc.PNG)
![Capture1](https://user-images.githubusercontent.com/83119962/115957102-38792f00-a51e-11eb-824d-ae886768db93.PNG)
![Capture3](https://user-images.githubusercontent.com/83119962/115957109-3ca54c80-a51e-11eb-9e09-951cfcd5a62b.PNG)

**Comment by kmuehlbauer** [comment]
Hi @babuvanam, how did you call your program?

**Comment by kmuehlbauer** [comment]
@babuvanam Can you show the out put of:

`(wradlib) C:\Users\LENOVO>python -c "import wradlib; wradlib.show_versions()"`

**Comment by babuvanam** [comment]
Hello @kmuehlbauer,thanks for your response,i executed my program in spyder IDE the following is the error i am getting.
![Capture4](https://user-images.githubusercontent.com/83119962/116035573-d38b1980-a682-11eb-847f-f25f56384805.PNG)
and output of   (wradlib) C:\Users\LENOVO>python -c "import wradlib; wradlib.show_versions()" is
![Capture5](https://user-images.githubusercontent.com/83119962/116035615-ec93ca80-a682-11eb-907b-120498a2c8dd.PNG)

**Comment by kmuehlbauer** [comment]
@babuvanam That's a common issue with IDE's like `spyder`. You need to make sure, that `spyder` can use  the `wradlib`-environment.

Please read this: https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder
I would suggest to follow the modular approach: https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#the-modular-approach

**Comment by babuvanam** [comment]
> @babuvanam That's a common issue with IDE's like `spyder`. You need to make sure, that `spyder` can use the `wradlib`-environment.
> 
> Please read this: https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder
> I would suggest to follow the modular approach: https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#the-modular-approach

now i am getting this error 
![Capture6](https://user-images.githubusercontent.com/83119962/116044109-24543f80-a68e-11eb-9862-aeaeccfd8da9.PNG)
what is environment?how to set it?
my anaconda path is C:\ProgramData\Anaconda3
spyder path is C:\Users\LENOVO
and wradlib path is C:\Users\LENOVO\.conda\envs
how to set these paths?please clarify

**Comment by kmuehlbauer** [comment]
@babuvanam You would need to install spyder-kernels as suggested by the error-message.

`(wradlib) C:\Users\LENOVO>conda install spyder-kernels`

I do not use `spyder` and I'm not familiar with this IDE. So you would need to find out yourself. A good starting point is usually the documentation (https://docs.spyder-ide.org/current/index.html). I'm closing this, as this is no wradlib question but a spyder-ide question.

**Comment by babuvanam** [comment]
> @babuvanam You would need to install spyder-kernels as suggested by the error-message.
> 
> `(wradlib) C:\Users\LENOVO>conda install spyder-kernels`
> 
> I do not use `spyder` and I'm not familiar with this IDE. So you would need to find out yourself. A good starting point is usually the documentation (https://docs.spyder-ide.org/current/index.html). I'm closing this, as this is no wradlib question but a spyder-ide question.

ok,thank you
