### ISSUE TITLE
Wradlib installation issue

### ISSUE THREAD

**Issue by akhil24jun** [wradlib/wradlib#582]
I have installed wradlib using anaconda. However, when i am trying to import the wradlib it is throwonh errors ModuleNotFoundError: No Module named 'requests'
The error message receiwbd along with conda liat and conda info is attached for your reference.
Please suggest.
![16597055697901226381526206250161](https://user-images.githubusercontent.com/35932886/183085878-3dde22e3-a92a-4695-bb2c-f8196693b8fa.jpg)
![16597056080833684061734198202648](https://user-images.githubusercontent.com/35932886/183085951-452861e6-0650-4d51-b408-ff0b1c9297ee.jpg)
 
![16597056614263265140468987380661](https://user-images.githubusercontent.com/35932886/183086083-a348f5c1-cf90-4328-8a6b-867181ffdd6a.jpg)
![16597056855646686951875239339337](https://user-images.githubusercontent.com/35932886/183086148-0aa8ba62-a995-4567-b05a-b0c0b3387449.jpg)
![16597057097447487701562400163469](https://user-images.githubusercontent.com/35932886/183086244-c73553fe-6386-461c-8264-1283ca463b14.jpg)

**Comment by kmuehlbauer** [comment]
@akhil24jun You have a very outdated wradlib version in your environment.

Please run `conda install wradlib=1.16.0` to get the latest version.

**Comment by kmuehlbauer** [comment]
Please check the command, it might need double == .

**Comment by kmuehlbauer** [comment]
@akhil24jun Do you need further help with that issue?

**Comment by akhil24jun** [comment]
Hi, @kmuehlbauer 
I am working to install the wradlib 1.16.0 and will then check whether it's working or not.
I will update regarding the same in sometime,
![wradlib-08-08-2022](https://user-images.githubusercontent.com/35932886/183347928-d5a10626-7aea-4c8b-ad3d-c9671f1fd983.jpg)

**Comment by kmuehlbauer** [comment]
@akhil24jun I see that you are installing in the (base) environment. This is not good practise. In fact it is recommended to create a new environment for different use cases.

```
(base) $ conda create -n wradlib python=3.10 wradlib
(base) $ conda activate wradlib
(wradlib) $
```

**Comment by akhil24jun** [comment]
@kmuehlbauer Thank you very much for the support.
The latest version is working fine.
![wradlib-08-08-2022](https://user-images.githubusercontent.com/35932886/183352158-746b0970-bee8-40cc-8f34-a0c4259a3595.jpg)

**Comment by kmuehlbauer** [comment]
@akhil24jun Great news. If you are running into problems using wradlib, please open issues. I'll close this one.
