### ISSUE TITLE
bias in georef.sweep_centroids

### ISSUE THREAD

**Issue by egouden** [wradlib/wradlib#60]
There is an awful bug in  georef.sweep_centroids (my code).
In ascale definition 2*pi should be used instead of pi.

ascale = np.pi / nrays => ascale = 2*np.pi / nrays

This function is not used by any other library functions.
It is used in the coord.py example (a kind of test).
Hopefully no one (expect me) has used it.

Regards,

Edouard

**Comment by kmuehlbauer** [comment]
@egouden Thanks for reporting this. 

The fix is tested in this branch https://github.com/wradlib/wradlib/tree/fix_ascale. It will get merged when we have a green build.
