### ISSUE TITLE
Loading just a subset of large vector files as VectorSource

### ISSUE THREAD

**Issue by plvoit** [wradlib/wradlib#624]
When dealing with very large shapefiles it would be very convenient if it was possible to load just partially load shapefiles, as it is for example possible with Geopandas (using a vector mask or a bounding box):

```
gdf = gpd.read_file("/path", mask=shape)   #or
gdf = gpd.read_file("/path", bbox=bbox) 
```

This feature would help to speed up large computations on HPCs.

There would be workarounds for this.
1. Open a subset of a vector file, transform it to json and then open a VectorSource from this json:

```
subset = gpd.read_file("/path", mask=shape) .to_json()
vector = wrl.VectorSource(subset)
```
However, there is a problem because wradlib assumes that the projection of the json is EPSG:4326. If the data has a different projection the creation of VectorSource creates an error. This issue can also not be solved by using the argument "projection_source".
If, for instance, the data has the projection EPSG:3035, following error occurs:

```
subset = gpd.read_file("/path", mask=shape)
srs = ogr.osr.SpatialReference()
srs.ImportFromEPSG(subset.crs.to_epsg())
json = gpd.read_file("/path", mask=shape) .to_json()
vector = wrl.VectorSource(subset)

RuntimeError: PROJ: laea: Invalid latitude
```

2. Another nice solution would be, if it was possible to just transform Geodataframes directly to VectorSource without writing them on disk first.

3. An option for VectorSource to read just a subset of the data without loading the whole from disk first.

#### Version

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) 
[GCC 10.4.0]
python-bits: 64
OS: Linux
OS-release: 5.19.0-41-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: ('en_GB', 'UTF-8')
libhdf5: 1.10.6
libnetcdf: 4.8.0
xarray: 2022.11.0
pandas: 1.3.4
numpy: 1.21.4
scipy: 1.7.3
netCDF4: 1.5.7
pydap: None
h5netcdf: 0.11.0
h5py: 3.3.0
Nio: None
zarr: None
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.8
cfgrib: 0.9.8.5
iris: None
bottleneck: None
dask: 2022.04.0
distributed: 2022.4.0
matplotlib: 3.5.1
cartopy: 0.20.0
seaborn: 0.11.2
numbagg: None
fsspec: 2023.3.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 67.6.0
pip: 23.0.1
conda: None
pytest: 6.2.5
IPython: 8.11.0
sphinx: 6.1.3
wradlib: 1.19.1

**Comment by kmuehlbauer** [comment]
@plvoit With wradlib 2.0 coming up, there are quite some changes in the internals of VectorSource. So it's for instance not possible anymore to load vector files with missing projection information. I'll close this for now, please feel free to reopen after checking wradlib 2.0.
