### ISSUE TITLE
Quick help: ValueError: cannot reshape array of size 0 into shape (0,newaxis)

### ISSUE THREAD

**Issue by Miron025** [wradlib/wradlib#633]
I loaded 24 h of data from Dresden and still getting this error...maybe some radar images were possibly damaged or improperly loaded. 
Only pm = vol[0] / 5,5 el. can be loaded. But I need to view lower elevations...

ValueError: cannot reshape array of size 0 into shape (0,newaxis)

vol = wrl.io.RadarVolume()
for r, v in zip(volume_reflectivity, volume_velocity):
    ds0 = wrl.io.open_odim_mfdataset(r, group="dataset1",
                                     concat_dim="time",
                                     combine="nested",
                                    )
    ds1 = wrl.io.open_odim_mfdataset(v, group="dataset1",
                                     concat_dim="time",
                                     combine="nested",
                                    )

    vol.append(xr.merge([ds0, ds1], combine_attrs="override"))
    vol.sort(key=lambda x: x.time.min().values)

Error message in .txt file

Is there any way how to save and view the data before they will be deleted from DWD folders? 

Wradlib and python fully updated everything working fine (other stations). 

[errormessage.txt](https://github.com/wradlib/wradlib/files/12172245/errormessage.txt)

**Comment by Miron025** [comment]
Any help? Today the same error while loading 4 hours of data from DRS, only vol=0 can be viewed, lower elevations resulted in this annyoing error and making it unable to see the whole radar image (the lowest scans).

**Comment by kmuehlbauer** [comment]
Sorry for the delay here. Unfortunately the stacktrace in the above errormessage.txt is not complete. Please use the Bug-report template and provide the necessary information. Thanks!

**Comment by kmuehlbauer** [comment]
Please reopen with added information. Thanks.
