### ISSUE TITLE
wradlib 2.0 release candidates

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradlib#637]
This issue keeps track of any issues which are related to the wradlib 2.0 release candidates.

- [x] use community package cmweather 
- [x] fix any remaining documentation issues (links, wording etc.)
- [x] fix notebooks (cleanup, simplify etc.)
- [ ] tbc.

**Comment by kmuehlbauer** [comment]
Release is finally done. :tada: :rocket: :shipit: :package:

**Comment by amotl** [comment]
Wonderful. Kudos for your amazing work here!
