### ISSUE TITLE
Problems with wrl.georef.reproject() 

### ISSUE THREAD

**Issue by Teralaw** [wradlib/wradlib#662]
Hi,
I have some problems with example code from the documentation [command wrl.georef.reproject()].

#### MCVE Code Sample

```python
import wradlib as wrl
from osgeo import osr

proj_stereo = wrl.georef.create_osr("dwd-radolan")
print(proj_stereo)
proj_wgs = osr.SpatialReference()
proj_wgs.ImportFromEPSG(4326)
print(proj_wgs)

radolan_grid_xy = wrl.georef.get_radolan_grid(1100, 900)
radolan_grid_ll = wrl.georef.reproject(
    radolan_grid_xy, projection_source=proj_stereo, projection_target=proj_wgs
)
print(
    "{0}, ({1:.4f}, {2:.4f})".format(radolan_grid_ll.shape, *radolan_grid_ll[0, 0, :])
)
```

#### Expected Output
Transformed coordinates in wgs84 space Germany.

#### Problem Description

I am trying to transform the coordinates from the radolan grid (1100 x 900) provided by wradlib into wgs 84 coordinates (EPSG: 4326) with the code shown below. The code used comes from the documentation of wrablib (https://docs.wradlib.org/projects/old-docs/en/1.19.0/notebooks/fileio/radolan/radolan_grid.html) and was adopted except for the size of the grid. In contrast to the results shown in the documentation, we get the following output for the last print command:
`(1100, 900, 2), (-443.4622, -4758.6447)`
All other entries in the radolan_grid_xy and radolan_grid_ll arrays also match.
For the previous creation of the coordinate systems we get the same output for the print commands.

#### Version

<details><summary>Output of <tt>wrl.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: ('de_DE', 'cp1252')
libhdf5: 1.14.3
libnetcdf: 4.9.2

xarray: 2023.12.0
pandas: 2.1.4
numpy: 1.26.3
scipy: 1.11.4
netCDF4: 1.6.5
pydap: None
h5netcdf: 1.3.0
h5py: 3.10.0
Nio: None
zarr: None
cftime: 1.6.3
nc_time_axis: None
iris: None
bottleneck: None
dask: 2023.12.1
distributed: 2023.12.1
matplotlib: 3.8.2
cartopy: 0.22.0
seaborn: None
numbagg: None
fsspec: 2023.12.2
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 68.2.2
pip: 23.3.1
conda: None
pytest: None
mypy: None
IPython: 8.20.0
sphinx: 7.2.6

wradlib: 2.0.3

</details>

**Comment by kmuehlbauer** [comment]
@Teralaw Is this still an issue for you? Please reopen with more details.
