### ISSUE TITLE
sample code for classify_echo_fuzzy

### ISSUE THREAD

**Issue by kojinsan** [wradlib/wradlib#67]
I would be appreciate if you can provide a sample code for the Kdp based dual-pol rain fall estimation, especially on the usage of classify_ech_fuzzy. Thank very much.
Jin-san Ko

**Comment by heistermann** [comment]
Thanks for this suggestion! Please watch the status of this issue in order to stay updated on the implementation progress.

**Comment by irenemeanspeace** [comment]
Hi Jin-san,

I made a [notebook](https://nbviewer.jupyter.org/github/irenemeanspeace/phirad/blob/master/clutter/Clutter%20detection%20using%20polarimetric%20approach%20%28EDGE%20netcdf%29.ipynb) on clutter detection using a polarimetric approach, and here it is shown how to use the `classify_echo_fuzzy` function. I'll make another one for the KDP based rainfall estimation.

Hope this helps,
irene

**Comment by irenemeanspeace** [comment]
Hi Jin-san,

Here's another [notebook](https://nbviewer.jupyter.org/github/irenemeanspeace/phirad/blob/master/rainfall%20estimation/Rainfall%20estimation%20from%20KDP%20%28without%20clutter%20correction%29.ipynb) showing an example on how to do the kdp-based rainfall estimation.

Let me know if you have any questions.

Cheers,
irene

**Comment by kojinsan** [comment]
Thank. I will study it.

從我的 iPad 傳送

**Comment by heistermann** [comment]
Thanks, Irene! Im closing this issue. However, we should think about adopting these notebooks in wradlib docs under "Tutorials and Examples". I will look into that.
