### ISSUE TITLE
xarray accessor for georef.bin_distance() computes bin altitude

### ISSUE THREAD

**Issue by katelbach** [wradlib/wradlib#675]
Using the wradlib xarray accessor for bin_distance() yields the same result as bin_altitude(). After taking a look at the code I believe that Line 179 in [georef/misc.py](https://github.com/wradlib/wradlib/blob/main/wradlib/georef/misc.py#L179) should be 
out = _apply_ufunc_wrapper(obj, bin_distance) 

instead of 
out = _apply_ufunc_wrapper(obj, bin_altitude)

#### MCVE Code Sample

```python
from open_radar_data import DATASETS
import xradar as xd
import xarray as xr

filename = DATASETS.fetch("71_20181220_060628.pvol.h5")
ds = xr.open_dataset(filename, group="sweep_0", engine="odim")

print(ds.wrl.georef.bin_distance())
print(ds.wrl.georef.bin_altitude())

```

#### Expected Output
great circle distance from radar site to radar bin

#### Problem Description
we actually get the altitude of the bin

#### Version

<details><summary>Output of <tt>wrl.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
python-bits: 64
OS: Linux
OS-release: 6.8.0-40-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_AT.utf8
LOCALE: ('de_AT', 'UTF-8')
libhdf5: 1.14.3
libnetcdf: 4.9.2
xarray: 2024.7.0
pandas: 2.2.2
numpy: 2.1.0
scipy: 1.14.1
netCDF4: 1.7.1
pydap: None
h5netcdf: 1.3.0
h5py: 3.11.0
zarr: None
cftime: 1.6.4
nc_time_axis: None
iris: None
bottleneck: None
dask: 2024.8.1
distributed: 2024.8.1
matplotlib: 3.9.2
cartopy: 0.23.0
seaborn: None
numbagg: None
fsspec: 2024.6.1
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 72.2.0
pip: 24.2
conda: None
pytest: 8.3.2
mypy: None
IPython: None
sphinx: None
wradlib: 2.1.0

</details>

**Comment by kmuehlbauer** [comment]
@katelbach Thanks! What a mess! This is most likely a regression for the 2.0 wradlib version ( a copy and paste failure :cry:)

Luckily that didn't affect the georeferencing as there `site_distance` is used.
