### ISSUE TITLE
Projection mismatch in RADOLAN RY product?

### ISSUE THREAD

**Issue by guidocioni** [wradlib/wradlib#678]
Today I was trying to plot some data from the RADOLAN RY composite. As far as I understand, this product should be the closest to 5-minutes precipitation rate estimation from reflectivity (after some quality correction).

I'm using the `xarray` reader by reading a bunch of files. 
```python
ds = xr.open_mfdataset('radar_data/raa01-ry_10000-*-dwd---bin', engine='radolan')
```
This automatically reads the coordinates and the time (which I suppose should be in UTC). 

After I'm plotting with 

```python
tile_source = cimgt.MapboxTiles(access_token=os.environ['MAPBOX_KEY'], map_id='dark-v10')

fig, axis = plt.subplots(1, 1,
                         subplot_kw=dict(projection=tile_source.crs),
                         figsize=(15, 15))
axis.set_extent([8.38, 10.78, 53., 54.17],  crs=ccrs.PlateCarree())
axis.add_image(tile_source, 8, interpolation='spline36')

x2d, y2d = np.meshgrid(ds.x, ds.y)
data = ds.sel(time="2024-09-04 04:15", method='nearest')['RY']

map_proj = ccrs.Stereographic(
    true_scale_latitude=60.0, central_latitude=90.0, central_longitude=10.0
)

c = axis.pcolormesh(
    x2d,
    y2d,
    data.values,
    transform=map_proj,
)
```

Note that I'm transforming the data from the original resolution(`map_proj`) to the destination projection (the Mercator used by the tiles, `tile_source.crs`).
This is the resulting plot yesterday at 04:15 UTC 

![6e342624-ba2c-4626-9a57-fb4e17a0fc10](https://github.com/user-attachments/assets/88ddc958-7efb-409e-82ec-a03a09727138)

I was trying to compare to some other products available online but I noticed some mismatch in the thunderstorm positions. For example here is a comparable picture which should also come from RADOLAN data.

![de_px250-de-320-1_2024_09_04_42_0415](https://github.com/user-attachments/assets/f6b73db3-b199-4ace-a680-dd4c6f169068)

What could explain the shift in the cells? I thought it was a timestamp mismatch, but it seems more to be a geometrical transformation issue. Any idea what I'm doing wrong?

**Comment by kmuehlbauer** [comment]
@guidocioni How does the image look like, if you use plain wradlib/cartopy/xarray plotting along  https://docs.wradlib.org/en/latest/notebooks/fileio/radolan/radolan_quickstart.html?

The features would have to be added to see the borders/rivers in der image.

**Comment by kmuehlbauer** [comment]
Do you know what transformation engine matplotlib uses under the hood?

**Comment by guidocioni** [comment]
> Do you know what transformation engine matplotlib uses under the hood?

isn't cartopy taking care of that? I'd suppose this to be quite mature as feature because I used the `transform` argument before and never noticed errors.
Maybe the original map projection I'm specifying doesn't coincide with the original one?

**Comment by guidocioni** [comment]
to be fair I'm also assuming the projection used by Kachelmann is 100% correct, which may not be true

**Comment by guidocioni** [comment]
Hey @kmuehlbauer I have some updates but you'll need to help me understand what is going on when using the readers (included the xarray one) because there is definitely something weird going on. 
First of all, as you suggested, I tried to use the default reader

```python
data, attrs = wrl.io.read_radolan_composite("radar_data/raa01-ry_10000-2409040415-dwd---bin")
radolan_grid_xy = wrl.georef.get_radolan_grid(900, 900)
data = np.ma.masked_equal(data, -9999) * 20

fig = plt.figure(figsize=(10, 8))
ax = plt.axes(projection=ccrs.Stereographic(
    true_scale_latitude=60.0, central_latitude=90.0, central_longitude=10.0
))
ax.set_extent([5, 15, 47., 54.17], crs=ccrs.PlateCarree())
x = radolan_grid_xy[:, :, 0]
y = radolan_grid_xy[:, :, 1]
pm = ax.pcolormesh(x, y, data, cmap=cmap, norm=norm)
ax.add_feature(cfeature.BORDERS.with_scale('10m'), edgecolor='black', zorder=5)
ax.add_feature(cfeature.COASTLINE.with_scale('10m'), edgecolor='black', zorder=5)
```

Note that I'm choosing the figure `projection` to coincide with the RADOLAN one. However, it seems the coordinates obtained like this are wrong because I'm getting an empty plot.

![e23e73d7-4247-4926-a8d2-081a66c288a7](https://github.com/user-attachments/assets/25472034-a97a-4304-b348-550f70112bc8)

If I remove the call to the set extents then the radar data is plotted, but not the geo features, which means there is some mismatch in the `x` and `y`. 

![567c17c9-a6e2-4e55-bd00-890772e19c2c](https://github.com/user-attachments/assets/2de306a7-f185-4f28-b3d5-2ff4dd516c5f)

Then, I saw there is a `wgs84` option when reading the coordinates, so I tried to use that

```python
data, attrs = wrl.io.read_radolan_composite("radar_data/raa01-ry_10000-2409040415-dwd---bin")
data = np.ma.masked_equal(data, -9999) * 20
radolan_grid_xy = wrl.georef.get_radolan_grid(900, 900, wgs84=True)
fig = plt.figure(figsize=(15, 15))
ax = plt.axes(projection=ccrs.Stereographic(
    true_scale_latitude=60.0, central_latitude=90.0, central_longitude=10.0
))
ax.set_extent([5, 15, 47., 54.17], crs=ccrs.PlateCarree())
x = radolan_grid_xy[:, :, 0]
y = radolan_grid_xy[:, :, 1]
pm = ax.pcolormesh(x, y, data, cmap=cmap, norm=norm, transform=ccrs.PlateCarree())
cb = fig.colorbar(pm, shrink=0.2)
ax.add_feature(cfeature.BORDERS.with_scale('10m'), edgecolor='black', zorder=5)
ax.add_feature(cfeature.COASTLINE.with_scale('10m'), edgecolor='black', zorder=5)
ax.set_extent([8.38, 10.78, 53., 54.17], crs=ccrs.PlateCarree())
states_provinces = cfeature.NaturalEarthFeature(
        category='cultural',
        name='admin_1_states_provinces_lines',
        scale='10m',
        facecolor='none')
ax.add_feature(states_provinces, edgecolor='black', zorder=5)
```

Note that now the figure has the same projection, **but the data not anymore so I have to use the `transform` option when calling `pcolormesh`.**
This surprisingly works! I get the right results, which are clearly the same one shown in the kachelmann picture (i also checked other sources and this seems to be correct).

![dc5e6af2-7562-4de6-890f-4eab9ce16011](https://github.com/user-attachments/assets/b3fc950f-ef34-432e-ab27-29efd3ebef24)

If I try to do the same using directly the xarray reader (`ds = wrl.io.open_radolan_dataset("radar_data/raa01-ry_10000-2409040415-dwd---bin"`) I get the wrong result

![c0a0ebf3-5e87-458a-bef3-f7134762ddb2-1](https://github.com/user-attachments/assets/1331053d-bc2b-4e90-9ab4-2f5ac780cf1e)

So, there is something wrong going on in the reprojection when using the xarray backend (plus some error that I cannot understand when just reading the original grid). It seems this feature should be buried somewhere inside `xradar` but I cannot really find where this reprojection is done!

Is there any way to use the `wgs84` option when calling the `xarray` reader?

**Comment by kmuehlbauer** [comment]
So, it seems, cartopy is to blame, or how it is handled. If I create the 2D mesh coordinates in WGS84 beforehand (as you did it too), everything looks nice:

```
x2d, y2d = np.meshgrid(ds.x, ds.y)
lon, lat = wrl.georef.reproject(x2d, y2d, src_crs=wrl.georef.create_osr("dwd-radolan-sphere"), trg_crs=wrl.georef.get_default_projection())

data = ds.sel(time="2024-09-04 04:15", method='nearest')['RY']
data = data.where(data>0)

c = axis.pcolormesh(
    lon,
    lat,
    data.values,
    transform=ccrs.PlateCarree(),
    cmap="turbo",
)
```
![RY-hamburg](https://github.com/user-attachments/assets/e3b7a21b-6ef9-41f4-a0c5-cc20b801401b)



It seems that somehow the Cartopy transform using `Stereographic` is not working as expected

**Comment by guidocioni** [comment]
> So, it seems, cartopy is to blame, or how it is handled. If I create the 2D mesh coordinates in WGS84 beforehand (as you did it too), everything looks nice:
> 
> ```
> x2d, y2d = np.meshgrid(ds.x, ds.y)
> lon, lat = wrl.georef.reproject(x2d, y2d, src_crs=wrl.georef.create_osr("dwd-radolan-sphere"), trg_crs=wrl.georef.get_default_projection())
> 
> data = ds.sel(time="2024-09-04 04:15", method='nearest')['RY']
> data = data.where(data>0)
> 
> c = axis.pcolormesh(
>     lon,
>     lat,
>     data.values,
>     transform=ccrs.PlateCarree(),
>     cmap="turbo",
> )
> ```
> 
> ![RY-hamburg](https://private-user-images.githubusercontent.com/5821660/365121084-e3b7a21b-6ef9-41f4-a0c5-cc20b801401b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTY4MTEsIm5iZiI6MTcyNTYxNjUxMSwicGF0aCI6Ii81ODIxNjYwLzM2NTEyMTA4NC1lM2I3YTIxYi02ZWY5LTQxZjQtYTBjNS1jYzIwYjgwMTQwMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDk1NTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ0MjZmNTU1M2Q3MjJmMTkyMTFhYzFhYTczNThkZjU4NzdmYjc5ZmIyMDIxYzYzNWY3MGEwNzlmMGM5Zjc1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8kuPaqPT2nnrDxbjud_E0KMu0-Zzlczx6roqsUQy6_o)
> 
> It seems that somehow the Cartopy transform using `Stereographic` is not working as expected

Ah ok. To be fair it doesn't surprise me because I had all sorts of issues with cartopy.
However, given that it is described on the `wradlib` doc, I thought many people have used `cartopy` and `wradlib` to plot RADOLAN data...right? How am I the first one discovering this? :) Or is this a corner case?

**Comment by kmuehlbauer** [comment]
Yes, probably, we would have to revisit that in the docs.

**Comment by guidocioni** [comment]
For the moment I'm manually replacing the coordinates that I'm using for the plot without transforming.
Should we open an issue in cartopy?

**Comment by kmuehlbauer** [comment]
@guidocioni A cartopy-only reproducer would be nice, yes.

**Comment by kmuehlbauer** [comment]
@guidocioni Could you please check this out:

```python
map_proj = ccrs.Stereographic(
    true_scale_latitude=60.0, central_latitude=90.0, central_longitude=10.0, globe=ccrs.Globe(ellipse="sphere")
)
```

**Comment by guidocioni** [comment]
> ```python
> globe=ccrs.Globe(ellipse="sphere")
> ```

Nice catch! Yes it does work like this :) 
Much better than the workaround I implemented. 

So there's definitely something to add to the doc :) 

If you're curious I noticed this because I was trying to compare flight tracks with radar data to see how planes deviate in case of severe weather, so a precise localization was really important. Here is the animation I was able to create based on the data. As soon as a thunderstorm arrives over Hamburg airport you can see the planes going into a hold over `RARUP` (that's a waypoint name).


https://github.com/user-attachments/assets/0973108c-d51f-4950-b491-8e935d6326bc

Thanks again for the help @kmuehlbauer, I will close this.

**Comment by kmuehlbauer** [comment]
@guidocioni Impressive animation :+1: I'm wondering how many planes can be on hold there, before they get diverted to other airports?

And yes, changes need to be made to the docs, definitely. Especially this one is overlooked quite easy.
