### ISSUE TITLE
can you give a example about OrdinaryKriging in ipol ?

### ISSUE THREAD

**Issue by shanyuk** [wradlib/wradlib#72]
`rain = ipol.interpolate(src, trg, data, ipol.OrdinaryKriging, nnearest=2)`
it shows  error : "numpy.linalg.linalg.LinAlgError: Singular matrix" ,

**Comment by heistermann** [comment]
Thanks for the suggestion - we will provide an example as soon as possible.

**Comment by kmuehlbauer** [comment]
@shanyuk You can reference code lines like this (You just need to click on the line number and copy the address from the browser):

https://github.com/wradlib/wradlib/commit/a7e899d1955e4ffeecc504ad0eb1fa1685522e67#diff-2732686ff11606e709ced2a8be7afaa7R501

Then your comment can be inside the corresponding issue and is not without reference.

@heistermann is very busy atm and might not have any cycles to look into this the next couple of days. I can't be of much help, but there might be a chance that @thpfaff can assist.

**Comment by heistermann** [comment]
@shanyuk: Does the problem still occur - could you please provide a full example to reproduce the error (including the data if necessary - or ideally with code that generates synthetic data).

Apart from that, you can now find a very simple application example of OK in [wradlib's interpolation tutorial] (http://wradlib.org/wradlib-docs/latest/notebooks/interpolation/wradlib_ipol_example.html).

**Comment by shanyuk** [comment]
Think you. I have solved the problem with the example.

**Comment by kmuehlbauer** [comment]
Thanks for the feedback, @shanyuk!
