### ISSUE TITLE
Finalize python2/3 transition

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradlib#8]
Although travis runs fine with the current setup, there might be additional changes left.

- [x] make version aware, #9

**Comment by kmuehlbauer** [comment]
@jjhelmus, you may dive in here, if you find time.

**Comment by jjhelmus** [comment]
@kmuehlbauer Are these any Python2/3 issues in particular you are worried about.

**Comment by kmuehlbauer** [comment]
For now everything runs fine on travis with the different python versions. So this can be closed. Any bugs that will show can be tackled in the future.
