### ISSUE TITLE
How to read rainbow Vol data

### ISSUE THREAD

**Issue by krishna1990ck** [wradlib/wradlib#85]
I have rainbow .vol files how to read using wradlib

**Comment by kmuehlbauer** [comment]
Have a look at this simple [example notebook](https://github.com/wradlib/wradlib/blob/master/notebooks/fileio/wradlib_load_rainbow_example.ipynb).

If that doesn't help you much, please share your vol-file somewhere.

**Comment by kmuehlbauer** [comment]
@krishna1990ck 

I answered on the list, but I reference it here also:
https://gist.github.com/wradlib/da25e2232af1c53ef931e481aec6ea76

If there is anything you further need, please reopen the issue.
