### ISSUE TITLE
Ipol breaking due to changes in scipy 0.18.0

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradlib#86]
When using scipy 0.18.0 the ipol notebook breaks while handling nan-data. Needs reworking. Pinned scipy to 0.17.1 within travis in #84.

**Comment by kmuehlbauer** [comment]
See this [travis-log](https://travis-ci.org/wradlib/wradlib/jobs/147456764).

**Comment by kmuehlbauer** [comment]
@heistermann Did you had the chance to look into this? Any ideas?

**Comment by heistermann** [comment]
@kmuehlbauer: Not yet, but asap. Thanks for pointing this out.

**Comment by heistermann** [comment]
Apparently related to this scipy/scipy#6515

Problem occurs in case the parameter `nnearest` is larger than the number of source points. I'll try to find a more generic solution.

**Comment by kmuehlbauer** [comment]
There were some changes in ckdtree implementation, but I‘m not sure, if this is effecting this. Let‘s see what the scipy devs say.

**Comment by heistermann** [comment]
Addressed by Pull Request #95.
